# Questions 1:

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np

In [3]:
arr = np.arange(2, 53, 3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Questions 2:

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
A=[11,25,3,4,5]
B=[6,77,8,69,10]
arr1=np.array(A)
arr2=np.array(B)

In [5]:
arr1 #list A converted to array

array([11, 25,  3,  4,  5])

In [6]:
arr2 #list B converted to array

array([ 6, 77,  8, 69, 10])

In [7]:
a=np.concatenate((arr1,arr2)) #array concatenation
a

array([11, 25,  3,  4,  5,  6, 77,  8, 69, 10])

In [8]:
np.sort(a) #sorting of concatenated array

array([ 3,  4,  5,  6,  8, 10, 11, 25, 69, 77])

# Questions 3:

Write a code snippet to find the dimensions of a ndarray and its size.

In [9]:
b=np.ndarray([3,4,2]) #ndarray
b

array([[[6.23042070e-307, 4.67296746e-307],
        [1.69121096e-306, 1.95820760e-306],
        [3.22643519e-307, 7.56599807e-307],
        [8.90104239e-307, 3.33776697e-307]],

       [[9.79054228e-307, 9.34598926e-307],
        [9.34583987e-307, 1.37961505e-306],
        [1.60219035e-306, 8.01097889e-307],
        [1.78020169e-306, 7.56601165e-307]],

       [[1.02359984e-306, 1.33510679e-306],
        [2.22522597e-306, 8.01097889e-307],
        [7.56595733e-307, 8.01091099e-307],
        [8.34445562e-308, 3.91792476e-317]]])

In [10]:
np.ndim(b) #dimension of ndarray

3

In [11]:
np.size(b) #size of ndarray

24

# Questions 4:
 
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet  
Hint: np.newaxis, np.expand_dims

# Converting  1D array to 2D array using np.newaxis

In [12]:
a1 = np.arange(4)
a1.shape

(4,)

In [13]:
row_vec = a1[np.newaxis, :]     # arr[None, :]
row_vec.shape

(1, 4)

In [14]:
row_vec #1D array

array([[0, 1, 2, 3]])

In [15]:
col_vec = a1[:, np.newaxis]     # arr[:, None]
col_vec.shape

(4, 1)

In [16]:
col_vec #converted to 2D array using np.newaxis

array([[0],
       [1],
       [2],
       [3]])

# Converting 1D array to 2D array using np.expand_dims

In [26]:
a1

array([0, 1, 2, 3])

In [27]:
np.ndim(a1)

1

In [17]:
a2 = np.expand_dims(a1, axis=(1,-2,3))
a2.shape

(4, 1, 1, 1)

In [22]:
np.ndim(a2)

4

# Questions 5:

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [23]:
f = np.array([1,2,3])
g = np.array([4,5,6])  

print('Horizontal Append:\n', np.hstack((f, g))) #using hstack()


Horizontal Append:
 [1 2 3 4 5 6]


In [24]:
f = np.array([1,2,3])
g = np.array([4,5,6])  

print('Vertical Append:\n', np.vstack((f, g)))  #using vstack()

Vertical Append:
 [[1 2 3]
 [4 5 6]]


# Questions 6:

How to get unique items and counts of unique items?

In [25]:
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a ,"\n")
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40] 

Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
